// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehzqfbklqqctqtslehpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoenFmYmtscXFjdHF0c2xlaHBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODU2ODAsImV4cCI6MjA3MzM2MTY4MH0.m7UVdZTON1YcdQoOqIBBch8KijUpQxi4PV-p8LwRrzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});